### ISSUE TITLE
SA LIFT export to Fieldworks in "not quite right"

### ISSUE THREAD

**Issue by megahirt** [sillsdev/SpeechAnalyzer#2]
@terrygibbs can you explain in detail what needs to be changed for the LIFT export to work correctly?

**Comment by darcywong00** [comment]
I'll try to recap from my discussion with @terrygibbs and @sdysart
Testing with Speech Analyzer 3.1.0.148 (MSEA)

With the attached SA project --> File --> Export --> Lift

Languages as selected:
![LIFT View Before - After](https://user-images.githubusercontent.com/7358010/120263996-0e5a2000-c2c7-11eb-9b84-e490a0f59406.jpg)

1. The audio file for the second segment `"bush nut"` fails to export because the quotes aren't escaped in the wav filename.
2.  When the lift file is generated, the language tags don't seem to be BCP-47 so Flex treats the writing systems differently
3. Even when "Phonemic" is unchecked, it still gets exported as "Abkhazian"

@sdysart can provide more details. I think he also mentioned "Pronunciations" need to be exported as Lexeme Form (IPA)

[terry.zip](https://github.com/sillsdev/SpeechAnalyzer/files/6573196/terry.zip)

**Comment by darcywong00** [comment]
> When the lift file is generated, the language tags don't seem to be BCP-47 so Flex treats the writing systems differently

This is likely gonna be a big hurdle. Unfortunately, I don't think we can drop in 
https://github.com/sillsdev/libpalaso/tree/master/SIL.WritingSystems

Wonder if we parse the langtags.json file from https://github.com/silnrsi/langtags/ for SA's language list...

**Comment by darcywong00** [comment]
This can be closed now. The remaining item (langtags.json) is handled in a separate issue.
